#!/bin/bash
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="coph" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copm" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=128 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=256 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="copw" --kfolds=5 --n_hidden_nn=512 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=128 --k_sort=91 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=128 --k_sort=91 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=128 --k_sort=91 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=128 --k_sort=91 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=128 --k_sort=91 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=256 --k_sort=91 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=256 --k_sort=91 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=256 --k_sort=91 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=256 --k_sort=91 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=256 --k_sort=91 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=512 --k_sort=91 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=512 --k_sort=91 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=512 --k_sort=91 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=512 --k_sort=91 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="8gaussians" --kfolds=5 --n_hidden_nn=512 --k_sort=91 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=128 --k_sort=12 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=128 --k_sort=12 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=128 --k_sort=12 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=128 --k_sort=12 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=128 --k_sort=12 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=256 --k_sort=12 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=256 --k_sort=12 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=256 --k_sort=12 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=256 --k_sort=12 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=256 --k_sort=12 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=512 --k_sort=12 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=512 --k_sort=12 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=512 --k_sort=12 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=512 --k_sort=12 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mushroom_folds" --kfolds=5 --n_hidden_nn=512 --k_sort=12 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=128 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=128 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=128 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=128 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=128 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=256 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=256 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=256 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=256 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=256 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=512 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=512 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=512 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=512 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="mnist_folds" --kfolds=3 --n_hidden_nn=512 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=128 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=128 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=128 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=128 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=128 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=256 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=256 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=256 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=256 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=256 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=512 --k_sort=2 --num_coupling=1 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=512 --k_sort=2 --num_coupling=2 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=512 --k_sort=2 --num_coupling=3 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=512 --k_sort=2 --num_coupling=4 --net_epochs=10 --prior_epochs=10
python main.py --dataset="genetic_folds" --kfolds=3 --n_hidden_nn=512 --k_sort=2 --num_coupling=5 --net_epochs=10 --prior_epochs=10
